modLoader="javafml"
loaderVersion="[33,)"
license="BSD-3-Clause"
issueTrackerURL="https://github.com/YaLTeR/MouseTweaks/issues"

[[mods]]
modId="mousetweaks"
version="${file.jarVersion}"
displayName="Mouse Tweaks"
updateJSONURL="http://play.sourceruns.org/yalter/MouseTweaks/update.json"
displayURL="https://minecraft.curseforge.com/projects/mouse-tweaks"
logoFile="mousetweaks_logo.png"
credits="Contributors: mezz, juliand665, panoskj."
authors="Ivan Molodetskikh (YaLTeR)"
description='''
THIS VERSION OF THE MOD HAS BEEN MODIFIED BY THE NEW WIND TEAM

A mod that enhances the inventory management by adding various additional functions to the usual mouse buttons.
'''
